# Use container-based infrastructure
sudo: false

services:
  - docker


language: java

jdk:
  - oraclejdk8

before_script:
  - ./gradlew build -x test
  - docker build --tag=bimgur .
  - docker run -d -p 8080:8080 -p 5433:5432 bimgur

script:
  - ./gradlew test -PrunIntegrationTests

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/